apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: moves-like-swagger-testing
spec:
  stepTemplate:
    env:
    - name: HOME
      value: /tekton/home
    - name: GIT_TOKEN
      valueFrom:
        secretKeyRef:
          name: openapi-pkg-gen
          key: auth-token
    - name: GIT_USER
      valueFrom:
        secretKeyRef:
          name: openapi-pkg-gen
          key: user
    envFrom:
    - secretRef:
        name: jx-boot-job-env-vars
        optional: true
    name: ""
    resources: {}
    workingDir: /workspace/source
  steps:
  - image: jx3mqubebuild.azurecr.io/spring-financial-group/jx3-openapi-generation:1.3.33
    name: package-generation
    resources: {}
    imagePullPolicy: Always
    script: |
      #!/bin/bash
      source /workspace/source/.jx/variables.sh
      
      git config --global --add safe.directory /workspace/source
      git config --global user.name ${GIT_AUTHOR_NAME:-jenkins-x-bot}
      git config --global user.email ${GIT_AUTHOR_EMAIL:-jenkins-x@googlegroups.com}
      
      jx3-openapi-generation generate pkg $OutputLanguages
  workspaces:
  - description: Pipeline for testing package generation in other service's PRs
    mountPath: /workspace
    name: output
