apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: moves-like-swagger
spec:
  stepTemplate:
    env:
    - name: HOME
      value: /tekton/home
    - name: GIT_TOKEN
      valueFrom:
        secretKeyRef:
          name: openapi-pkg-gen
          key: auth-token
    - name: GIT_USER
      valueFrom:
        secretKeyRef:
          name: openapi-pkg-gen
          key: user
    - name: PYX_API_KEY
      valueFrom:
        secretKeyRef:
          name: pyx
          key: api-key
    envFrom:
    - secretRef:
        name: jx-boot-job-env-vars
        optional: true
    name: ""
    resources: {}
    workingDir: /workspace/source
  steps:
  - image: jx3mqubebuild.azurecr.io/spring-financial-group/jx3-openapi-generation:latest
    name: package-generation
    resources: {}
    script: |
      #!/bin/bash
      source /workspace/source/.jx/variables.sh

      git config --global --add safe.directory /workspace/source
      git config --global user.name mqube-bot
      git config --global user.email mqube-bot@mqube.com

      jx3-openapi-generation generate pkg $OutputLanguages
  workspaces:
  - description: Generates client packages for the given languages
    mountPath: /workspace
    name: output
