apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: moves-like-swagger
spec:
  stepTemplate:
    env:
    - name: HOME
      value: /tekton/home
    - name: GIT_TOKEN
      valueFrom:
        secretKeyRef:
          name: openapi-pkg-gen
          key: auth-token
    - name: GIT_USER
      valueFrom:
        secretKeyRef:
          name: openapi-pkg-gen
          key: user
    envFrom:
    - secretRef:
        name: jx-boot-job-env-vars
        optional: true
    name: ""
    resources: {}
    workingDir: /workspace/source
  steps:
  - image: jx3mqubebuild.azurecr.io/spring-financial-group/jx3-openapi-generation:56507509dc472369a2da9e305020f20baf661169
    name: package-generation
    resources: {}
    script: |
      #!/bin/bash
      source /workspace/source/.jx/variables.sh
      
      jx3-openapi-generation generate pkg $OutputLanguages
  workspaces:
  - description: Generates client packages for the given languages
    mountPath: /workspace
    name: output
