apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: csharp-swagger
spec:
  stepTemplate:
    env:
    - name: HOME
      value: /tekton/home
    envFrom:
    - secretRef:
        name: jx-boot-job-env-vars
        optional: true
    name: ""
    resources: {}
  steps:
  - image: ghcr.io/jenkins-x/jx-promote:0.0.234
    name: set-version-csharp
    resources: {}
    script: |
      #!/usr/bin/env sh
      pwd
      source /workspace/source/.jx/variables.sh
      sed -i 's/0.0.0/'$VERSION'/g' ./registry/package.json
    workingDir: /workspace/source
  - image: jx3mqubebuild.azurecr.io/spring-financial-group/jx3-openapi-generation:0.0.19
    name: csharp-swagger
    resources: {}
    script: |
      #!/usr/bin/env sh
      pwd
      source /workspace/source/.jx/variables.sh
      cd ./registry
      /CreateCsharpPackage.sh https://api-staging.jx.mqube.build/swagger/docs/v1/$SwaggerServiceName $VERSION Mqube.$SwaggerServiceName.Client
    workingDir: /workspace/source
  workspaces:
  - description: Swagger generation will occur on the staging url once it has been built.
    mountPath: /workspace
    name: output