apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: moves-like-swagger
spec:
  stepTemplate:
    env:
    - name: HOME
      value: /tekton/home
    envFrom:
    - secretRef:
        name: jx-boot-job-env-vars
        optional: true
    name: ""
    resources: {}
    workingDir: /workspace/source
  steps:
  - image: ghcr.io/jenkins-x/jx-promote:0.0.234
    name: set-version
    resources: {}
    script: |
      #!/usr/bin/env sh
      . /workspace/source/.jx/variables.sh
      sed -i 's/0.0.0/'$VERSION'/g' ./registry/package.json
  - image: jx3mqubebuild.azurecr.io/spring-financial-group/jx3-openapi-generation:1.3.33
    name: moves-like-swagger
    resources: {}
    script: |
      #!/usr/bin/env sh
      . /workspace/source/.jx/variables.sh
      yarn global add @openapitools/openapi-generator-cli@2.23.1
      
      SPEC_PATH=$(/FindOpenAPISpec.sh https://api-staging.jx.mqube.build/swagger/docs/v1/$SwaggerServiceName)
      /CreateAngularPackageV3.sh $SPEC_PATH
  workspaces:
  - description: Swagger generation will occur on the staging url once it has been built.
    mountPath: /workspace
    name: output
