apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: csharp-swagger
spec:
  stepTemplate:
    env:
    - name: HOME
      value: /tekton/home
    envFrom:
    - secretRef:
        name: jx-boot-job-env-vars
        optional: true
    name: ""
    resources: {}
    workingDir: /workspace/source
  steps:
  - image: ghcr.io/jenkins-x/jx-promote:0.0.234
    name: set-version-csharp
    resources: {}
    script: |
      #!/usr/bin/env sh
      . /workspace/source/.jx/variables.sh
      sed -i 's/0.0.0/'$VERSION'/g' ./registry/package.json
  - image: jx3mqubebuild.azurecr.io/spring-financial-group/jx3-openapi-generation:1.1.0
    name: csharp-swagger
    resources: {}
    script: |
      #!/bin/bash
      source /workspace/source/.jx/variables.sh

      SPEC_PATH=$(/FindOpenAPISpec.sh $SwaggerUrl)
      cd ./registry
      /CreateCsharpPackage.sh $SPEC_PATH $VERSION Mqube.$SwaggerServiceName.Client $REPO_OWNER $REPO_NAME
  workspaces:
  - description: Swagger generation will occur on the staging url once it has been built.
    mountPath: /workspace
    name: output
