apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: moves-like-swagger
spec:
  stepTemplate:
    env:
    - name: HOME
      value: /tekton/home
    - name: GIT_TOKEN
      valueFrom:
        secretKeyRef:
          name: openapi-pkg-gen
          key: auth-token
    - name: GIT_USER
      valueFrom:
        secretKeyRef:
          name: openapi-pkg-gen
          key: user
    envFrom:
    - secretRef:
        name: jx-boot-job-env-vars
        optional: true
    name: ""
    resources: {}
    workingDir: /workspace/source
  steps:
  - image: jx3mqubebuild.azurecr.io/spring-financial-group/jx3-openapi-generation:latest
    name: package-generation
    resources: {}
    script: |
      #!/bin/bash
      set -ex
      source /workspace/source/.jx/variables.sh

      git config --global --add safe.directory /workspace/source
      git config --global user.name ${GIT_AUTHOR_NAME:-jenkins-x-bot}
      
      echo "GIT_AUTHOR_NAME is ${GIT_AUTHOR_NAME}"
      echo "GIT_AUTHOR_EMAIL is ${GIT_AUTHOR_EMAIL}"
      echo "GIT_USER is ${GIT_USER}"
      
      jx3-openapi-generation generate pkg $OutputLanguages
  workspaces:
  - description: Generates client packages for the given languages
    mountPath: /workspace
    name: output
