apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: preview-csharp-swagger
spec:
  stepTemplate:
    env:
    - name: HOME
      value: /tekton/home
    envFrom:
    - secretRef:
        name: jx-boot-job-env-vars
        optional: true
    name: ""
    resources: {}
  steps:
  - image: ghcr.io/jenkins-x/jx-promote:0.0.234
    name: get-pod-ip-csharp
    resources: {}
    script: |
      #!/usr/bin/env sh
      . /workspace/source/.jx/variables.sh
      echo $(kubectl get services -A | grep jx-$REPO_OWNER-$APP_NAME-pr-$PULL_NUMBER | awk '$2 == "'$APP_NAME'" {print $4}') > pod_ip
      sed -i 's/0.0.0/0.0.'$PULL_NUMBER'-rc.'$BUILD_ID'/g' ./registry/package.json
    workingDir: /workspace/source
  - image: jx3mqubebuild.azurecr.io/spring-financial-group/jx3-openapi-generation:0.1.8
    name: csharp-swagger
    resources: {}
    script: |
      #!/bin/bash
      source /workspace/source/.jx/variables.sh
      cd ./registry
      export PREVIEW_TIMESTAMP=$(date +%s)
      
      SWAG_PATH=$(find /workspace/source -type f -name "swagger.json")
      if test $SWAG_PATH ; then
        echo Swagger docs found in repository
      else
        SWAG_PATH=http://$(cat ../pod_ip):5000/swagger/v1/swagger.json
        echo Swagger docs not found in repository, using staging
      fi
      
      /CreateCsharpPackage.sh $SWAG_PATH 0.1.$PULL_NUMBER-preview-$PREVIEW_TIMESTAMP Mqube.$SwaggerServiceName.Client $REPO_OWNER $REPO_NAME
    workingDir: /workspace/source
  workspaces:
  - description: The git repo will be cloned onto the volume backing this workspace
    mountPath: /workspace
    name: output
