apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: generate-test-packages
spec:
  pipelineSpec:
    tasks:
      - name: from-build-pack
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go/pullrequest.yaml@versionStream
            name: ""
            resources:
              limits: {}
            workingDir: /workspace/source
            env:
              - name: SwaggerServiceName
                value: OpenAPIPkgGenerationMock
              - name: SpecPath
                value: /swagger.json
              - name: GIT_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: openapi-pkg-gen
                    key: auth-token
              - name: GIT_USER
                valueFrom:
                  secretKeyRef:
                    name: openapi-pkg-gen
                    key: user
          steps:
            - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
              name: ""
              resources: {}
            - image: ghcr.io/jenkins-x/jx-boot:3.2.197
              name: token-export
              resources: {}
              script: |
                #!/usr/bin/env sh
                jx gitops variables --commit=false
            - image: golang:1.18
              name: make-build
              resources: {}
              script: |
                #!/usr/bin/env bash
                source .jx/variables.sh
                make build
                mv ./build/jx3-openapi-generation ./mocks/jx3-openapi-generation
            - image: node:22
              name: test-package-generation
              imagePullPolicy: Always
              resources: {}
              script: |
                #!/bin/bash
                source /workspace/source/.jx/variables.sh
                npm install -g @openapitools/openapi-generator-cli@2.13.4
                apt-get update && apt-get install -y apt-transport-https openjdk-11-jdk default-jre zip
                cp ./openapitools.json /openapitools.json
                cd ./mocks
                ./jx3-openapi-generation generate packages python angular csharp java
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 1h0m0s
status: {}
