apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: generate-test-packages
spec:
  pipelineSpec:
    tasks:
      - name: from-build-pack
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go/pullrequest.yaml@versionStream
            name: ""
            resources:
              limits: {}
            workingDir: /workspace/source
            env:
              - name: SwaggerServiceName
                value: OpenAPIPkgGenerationMock
              - name: SpecPath
                value: /swagger.json
              - name: GIT_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: openapi-pkg-gen
                    key: auth-token
              - name: GIT_USER
                valueFrom:
                  secretKeyRef:
                    name: openapi-pkg-gen
                    key: user
              - name: PYX_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: pyx
                    key: api-key
          steps:
            - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
              name: ""
              resources: {}
            - image: ghcr.io/jenkins-x/jx-boot:3.2.197
              name: token-export
              resources: {}
              script: |
                #!/usr/bin/env sh
                jx gitops variables --commit=false
            - image: golang:1.24
              name: make-build
              resources: {}
              script: |
                #!/usr/bin/env bash
                source .jx/variables.sh
                echo "Building:"
                make build
                echo "Copying files:"
                cp ./mocks/swagger.json /workspace/source/swagger.json
                cp ./build/jx3-openapi-generation /workspace/source/jx3-openapi-generation
            - image: jx3mqubebuild.azurecr.io/spring-financial-group/jx3-openapi-generation:latest-preview
              name: test-package-generation
              imagePullPolicy: Always
              resources: {}
              script: |
                #!/bin/bash
                source /workspace/source/.jx/variables.sh
                git config --global --add safe.directory /workspace/source
                git config --global user.name ${GIT_AUTHOR_NAME:-mqube-bot}
                git config --global user.email ${GIT_AUTHOR_EMAIL:-mqube-bot@mqube.com}
                /workspace/source/jx3-openapi-generation test
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 1h0m0s
status: {}
